comment_width = 100
force_multiline_blocks = true
hard_tabs = true
max_width = 100
merge_imports = true
newline_style = "Unix"
trailing_comma = "Never"
unstable_features = true
use_field_init_shorthand = true
version = "Two"
wrap_comments = true
